### PR TITLE
fix/foodItemSchema added defaults

### PR DESCRIPTION
**Pull request by Thirdoptics**
- added default start date
- changed frequency default to 1

I believe this closes issue #262

### CODE REVIEW

**Comment by jspaine** [comment]
Looks good, @icpmacdo already has a fix in though. Think I'll give them a couple more days to fix the formatting otherwise I'll merge this one.

**Comment by icpmacdo** [comment]
Thanks for the leeway, I've been busy at work but will fix the formatting tonight.

**Comment by Thirdoptics** [comment]
thanks @jspaine, mostly just an exercise in getting familiar with git and jumping into projects to contribute and making sure I do things right.

**Comment by jspaine** [comment]
@Thirdoptics you seem to have it figured out :smile: I'll close this now the other one's merged.

**Pull request closed without merging**
