### PR TITLE
Fixed copyright year

### PR DESCRIPTION
**Pull request by dmcfaddengalway**
Changed the copyright year on client/modules/core/components/Footer.js fixes

### CODE REVIEW

**Comment by jspaine** [comment]
Hi, thanks but the issue was to make it automatic. So you'd need to find the date, get the year and show that.

**Comment by dmcfaddengalway** [comment]
Oh I can definitely do that for you! Mind if I continue with this issue

**Comment by jspaine** [comment]
Looks fine, but try and stick to the same style as the rest of the code - use const if possible or let, and no semicolons at the end of lines if possible.

**Comment by dmcfaddengalway** [comment]
Will fix right now!

Thank you and have a nice day,
     Daniel McFadden
     +353 (083) 8844332 (IRL)
     +1 (215) 350 4830 (US)
     dmcfaddengalway@gmail.com (primary)
     dmcfaddenhgp@gmail.com (secondary)

**Comment by jspaine** [comment]
Sorry for the delay, been moving.

And sorry but I meant use `const` if possible or `let` instead of `var` for variable declarations. It doesn't make any difference in this case but it's more consistent and generally a bit safer and more informative (this thing is constant, this is mutable). And the remaining `var`s are kind of a marker for old code that should maybe be updated.

Also there's no need for double curly braces around `year` in jsx.

**Comment by dmcfaddengalway** [comment]
@jspaine No worries! I did use `let` as I was under the impression that `const` would make its value not changable. But I will look into this more as I must have been confused. Will also change from `let` to `const` for you and resubmit.

I will fix the double curly braces around year. My bad, new to React.

**Comment by jspaine** [comment]
Awesome, thanks!

I didn't see let, maybe I missed it. But the value isn't going to change so const is right. It'll be set when the file is imported and stay the same until the app is closed or refreshed. So it won't update until a refresh if the app is kept open over the new year but I don't think that matters.

closes #199

**Comment by dmcfaddengalway** [comment]
@jspaine Looking back at it, it appears I must have actually put `var`, not `let` -- muscle memory. 

Oh okay, understand now. Thanks!

**Pull request merged**
